export const URL = 'https://norma.nomoreparties.space/api'
export const URL_MAIN = '/'
export const URL_LOGIN = '/login'
export const URL_REGISTER = '/register'
export const URL_FORGOT = '/forgot-password'
export const URL_RESET = '/reset-password'
export const URL_PROFILE = '/profile'
export const URL_INGREDIENTS = '/ingredients'
export const URL_INGREDIENT_DETAILS = '/ingredients/:id'
export const URL_ORDERS = '/orders'
export const URL_FEED = '/feed'

export const loaderStyles = 'position: absolute; top: 45vh; left: 50vw;'